/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'documents' : null } |
  { 'clothing' : null } |
  { 'accessories' : null } |
  { 'other' : null } |
  { 'keys' : null } |
  { 'pets' : null } |
  { 'wallet' : null } |
  { 'electronics' : null };
export interface Claim {
  'id' : string,
  'status' : Status,
  'itemId' : string,
  'createdAt' : bigint,
  'claimedBy' : Principal,
  'message' : string,
}
export interface Item {
  'id' : string,
  'status' : Status,
  'title' : string,
  'postedBy' : Principal,
  'date' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'itemType' : ItemType,
  'category' : Category,
  'location' : string,
}
export type ItemType = { 'found' : null } |
  { 'lost' : null };
export interface Stats {
  'totalFound' : bigint,
  'totalResolved' : bigint,
  'totalLost' : bigint,
  'totalClaims' : bigint,
}
export type Status = { 'resolved' : null } |
  { 'active' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClaim' : ActorMethod<[string, string], Claim>,
  'createItem' : ActorMethod<
    [ItemType, string, string, Category, string, string, string],
    Item
  >,
  'deleteItem' : ActorMethod<[string], undefined>,
  'getAllClaimsAdmin' : ActorMethod<[], Array<Claim>>,
  'getAllItemsAdmin' : ActorMethod<[], Array<Item>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClaimsForItem' : ActorMethod<[string], Array<Claim>>,
  'getItemById' : ActorMethod<[string], [] | [Item]>,
  'getItems' : ActorMethod<[], Array<Item>>,
  'getSimilarItems' : ActorMethod<[string], Array<Item>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserClaims' : ActorMethod<[], Array<Claim>>,
  'getUserItems' : ActorMethod<[], Array<Item>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClaimStatus' : ActorMethod<[string, Status], undefined>,
  'updateItemStatus' : ActorMethod<[string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];