/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Claim = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'itemId' : IDL.Text,
  'createdAt' : IDL.Int,
  'claimedBy' : IDL.Principal,
  'message' : IDL.Text,
});
export const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
export const Category = IDL.Variant({
  'documents' : IDL.Null,
  'clothing' : IDL.Null,
  'accessories' : IDL.Null,
  'other' : IDL.Null,
  'keys' : IDL.Null,
  'pets' : IDL.Null,
  'wallet' : IDL.Null,
  'electronics' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'itemType' : ItemType,
  'category' : Category,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Stats = IDL.Record({
  'totalFound' : IDL.Nat,
  'totalResolved' : IDL.Nat,
  'totalLost' : IDL.Nat,
  'totalClaims' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClaim' : IDL.Func([IDL.Text, IDL.Text], [Claim], []),
  'createItem' : IDL.Func(
      [ItemType, IDL.Text, IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text],
      [Item],
      [],
    ),
  'deleteItem' : IDL.Func([IDL.Text], [], []),
  'getAllClaimsAdmin' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'getAllItemsAdmin' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaimsForItem' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getItemById' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getSimilarItems' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'getUserItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClaimStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateItemStatus' : IDL.Func([IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Claim = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'itemId' : IDL.Text,
    'createdAt' : IDL.Int,
    'claimedBy' : IDL.Principal,
    'message' : IDL.Text,
  });
  const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
  const Category = IDL.Variant({
    'documents' : IDL.Null,
    'clothing' : IDL.Null,
    'accessories' : IDL.Null,
    'other' : IDL.Null,
    'keys' : IDL.Null,
    'pets' : IDL.Null,
    'wallet' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'itemType' : ItemType,
    'category' : Category,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Stats = IDL.Record({
    'totalFound' : IDL.Nat,
    'totalResolved' : IDL.Nat,
    'totalLost' : IDL.Nat,
    'totalClaims' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClaim' : IDL.Func([IDL.Text, IDL.Text], [Claim], []),
    'createItem' : IDL.Func(
        [ItemType, IDL.Text, IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text],
        [Item],
        [],
      ),
    'deleteItem' : IDL.Func([IDL.Text], [], []),
    'getAllClaimsAdmin' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'getAllItemsAdmin' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaimsForItem' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getItemById' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getSimilarItems' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'getUserItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClaimStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateItemStatus' : IDL.Func([IDL.Text, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };